// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: req_dispatcher/req_dispatcher.proto

package req_dispatcher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqDispatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ReqDispatchRequest) Reset() {
	*x = ReqDispatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_dispatcher_req_dispatcher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDispatchRequest) ProtoMessage() {}

func (x *ReqDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_req_dispatcher_req_dispatcher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDispatchRequest.ProtoReflect.Descriptor instead.
func (*ReqDispatchRequest) Descriptor() ([]byte, []int) {
	return file_req_dispatcher_req_dispatcher_proto_rawDescGZIP(), []int{0}
}

func (x *ReqDispatchRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ReqDispatchRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ReqDispatchRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReqDispatchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LatencyMs int32  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
}

func (x *ReqDispatchReply) Reset() {
	*x = ReqDispatchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_dispatcher_req_dispatcher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqDispatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDispatchReply) ProtoMessage() {}

func (x *ReqDispatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_req_dispatcher_req_dispatcher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDispatchReply.ProtoReflect.Descriptor instead.
func (*ReqDispatchReply) Descriptor() ([]byte, []int) {
	return file_req_dispatcher_req_dispatcher_proto_rawDescGZIP(), []int{1}
}

func (x *ReqDispatchReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ReqDispatchReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReqDispatchReply) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_req_dispatcher_req_dispatcher_proto protoreflect.FileDescriptor

var file_req_dispatcher_req_dispatcher_proto_rawDesc = []byte{
	0x0a, 0x23, 0x72, 0x65, 0x71, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x2f, 0x72, 0x65, 0x71, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x72, 0x65, 0x71, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x72, 0x22, 0x50, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x44, 0x69, 0x73, 0x70,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x63, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x44, 0x69,
	0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x73, 0x32, 0x63, 0x0a, 0x0d,
	0x52, 0x65, 0x71, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x12, 0x52, 0x0a,
	0x08, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12, 0x22, 0x2e, 0x72, 0x65, 0x71, 0x5f,
	0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x44, 0x69,
	0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x72, 0x65, 0x71, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x71, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x42, 0x28, 0x5a, 0x26, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x72, 0x65, 0x71,
	0x5f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_req_dispatcher_req_dispatcher_proto_rawDescOnce sync.Once
	file_req_dispatcher_req_dispatcher_proto_rawDescData = file_req_dispatcher_req_dispatcher_proto_rawDesc
)

func file_req_dispatcher_req_dispatcher_proto_rawDescGZIP() []byte {
	file_req_dispatcher_req_dispatcher_proto_rawDescOnce.Do(func() {
		file_req_dispatcher_req_dispatcher_proto_rawDescData = protoimpl.X.CompressGZIP(file_req_dispatcher_req_dispatcher_proto_rawDescData)
	})
	return file_req_dispatcher_req_dispatcher_proto_rawDescData
}

var file_req_dispatcher_req_dispatcher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_req_dispatcher_req_dispatcher_proto_goTypes = []interface{}{
	(*ReqDispatchRequest)(nil), // 0: req_dispatcher.ReqDispatchRequest
	(*ReqDispatchReply)(nil),   // 1: req_dispatcher.ReqDispatchReply
}
var file_req_dispatcher_req_dispatcher_proto_depIdxs = []int32{
	0, // 0: req_dispatcher.ReqDispatcher.Dispatch:input_type -> req_dispatcher.ReqDispatchRequest
	1, // 1: req_dispatcher.ReqDispatcher.Dispatch:output_type -> req_dispatcher.ReqDispatchReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_req_dispatcher_req_dispatcher_proto_init() }
func file_req_dispatcher_req_dispatcher_proto_init() {
	if File_req_dispatcher_req_dispatcher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_req_dispatcher_req_dispatcher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqDispatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_req_dispatcher_req_dispatcher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqDispatchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_req_dispatcher_req_dispatcher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_req_dispatcher_req_dispatcher_proto_goTypes,
		DependencyIndexes: file_req_dispatcher_req_dispatcher_proto_depIdxs,
		MessageInfos:      file_req_dispatcher_req_dispatcher_proto_msgTypes,
	}.Build()
	File_req_dispatcher_req_dispatcher_proto = out.File
	file_req_dispatcher_req_dispatcher_proto_rawDesc = nil
	file_req_dispatcher_req_dispatcher_proto_goTypes = nil
	file_req_dispatcher_req_dispatcher_proto_depIdxs = nil
}
